import Head from 'next/head';
import { useEffect } from 'react';
import { Container, Row, Col, Form, Button } from 'react-bootstrap';
import AdminLayout from '../../components/layouts/adminlayout';
import { useSession, getSession } from "next-auth/react";
import { useRouter } from 'next/router';


function Admin() {

  const router = useRouter();

  // const { data: session, status } = useSession();
  // if(status === "authenticated") {
  //   console.log(session);
  // }

  // useEffect(()=>{
  //   getSession().then(session => {
  //     if(!session) {
  //       router.push('/');
  //     }
  //   })
  // }, []);


  const { data: session, status } = useSession();

  //console.log(session);



  return (
    <>
      <Head>
        <title>Admin - Child mapping information system</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container fluid>
        <Row>
          <Col>
            <p>Welcome admin</p>
          </Col>
        </Row>
      </Container>
      
    </>

  )

};


Admin.layout = AdminLayout;
export default Admin;